=== killerswan/xmldemo/www/static/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="color" type="xs:string"/>

  <xs:element name="number" type="xs:string"/>

  <xs:element name="event">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="color"/>
        <xs:element ref="number"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="label" type="xs:string"/>

  <xs:attribute name="seqid" type="xs:string"/>

  <xs:element name="colorseq">
    <xs:complexType>
      <xs:attribute ref="seqid"/>
      <xs:sequence>
        <xs:element ref="label"/>
        <xs:element ref="event" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== killerswan/xmldemo/www/static/alpha.xml
<?xml version="1.0" encoding="UTF-8"?>

<colorseq seqid="1"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="schema.xsd">

  <label>alpha seq</label>

  <event>
    <color>#0ff</color>
    <number>7</number>
  </event>

  <event>
    <color>#0f0</color>
    <number>21</number>
  </event>

  <event>
    <color>#ff0</color>
    <number>3</number>
  </event>
</colorseq>

=== killerswan/xmldemo/www/static/beta.xml
<?xml version="1.0" encoding="UTF-8"?>

<colorseq seqid="2"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="schema.xsd">

  <label>beta seq</label>

  <event>
    <color>#0dd</color>
    <number>7</number>
  </event>

  <event>
    <color>#0d0</color>
    <number>2</number>
  </event>

  <event>
    <color>#dd0</color>
    <number>14</number>
  </event>
</colorseq>
